%Doctor.Config{
  ignore_modules: [
    # Spark/Ash/Jido generate helper modules that either point at `nofile` or
    # expand quoted DSL code in ways Doctor cannot attribute cleanly.
    ~r/^Inspect\.Bagu\.Demo\./,
    ~r/^Bagu\.Agent\.Dsl/,
    ~r/^Bagu\.Agent\.Verifiers\./,
    Bagu.Context,
    Bagu.Debug,
    Bagu.Error.Normalize,
    Bagu.Workflow.Build,
    Bagu.Workflow.Codegen,
    Bagu.Workflow.Definition,
    ~r/^Bagu\.Workflow\.Dsl/,
    ~r/^Bagu\.Demo\./,
    Bagu.Guardrails,
    ~r/^Bagu\.Guardrails\./,
    Bagu.Hooks,
    ~r/^Bagu\.Hooks\./,
    Bagu.ImportedAgent,
    ~r/^Bagu\.ImportedAgent\./,
    Bagu.Inspection,
    Bagu.Memory,
    ~r/^Bagu\.Plugins\./,
    Bagu.Skill,
    Bagu.StageRefs
  ],
  ignore_paths: [
    "nofile",
    ~r"^lib/mix/tasks/",
    ~r"^lib/bagu/error/normalize\.ex$",
    ~r"^lib/bagu/agent/",
    ~r"^lib/bagu/demo/",
    ~r"^lib/bagu/workflow/(build|codegen|definition|spark_dsl)\.ex$",
    ~r"^lib/bagu/workflow/dsl/",
    ~r"^lib/bagu/plugins/",
    ~r"^lib/bagu/imported_agent/(codec|registries)\.ex$",
    ~r"^lib/bagu/mcp/",
    ~r"^lib/bagu/subagent/"
  ],
  min_module_doc_coverage: 60,
  min_module_spec_coverage: 0,
  min_overall_doc_coverage: 90,
  min_overall_moduledoc_coverage: 100,
  min_overall_spec_coverage: 0,
  exception_moduledoc_required: true,
  raise: false,
  reporter: Doctor.Reporters.Full,
  struct_type_spec_required: false,
  umbrella: false
}
